name: payload-dumper-actions

on:
  workflow_dispatch:
    inputs:
      partition:
        description: 'partition'
        required: true
        default: 'boot'
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: ''


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install depedencies
        run: |
          mkdir tmp
          wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.0/payload-dumper-go_1.2.0_linux_amd64.tar.gz -P tmp/
          tar zxvf ./tmp/payload-dumper-go_1.2.0_linux_amd64.tar.gz -o payload-dumper-go
          
      - name: Download ROM
        run: |
          wget -O ./tmp/ROM.zip  ${{ github.event.inputs.ROM_URL }}

      - name: Dump payload.bin
        run: |
          ./payload-dumper-go -p ${{ github.event.inputs.partition }} -o output ./tmp/ROM.zip
          rm -rf tmp/
          rm payload-dumper-go
          tar -zcvf ./images.tgz ./output/*.img

          
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: './images.tgz'
